<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>ZMK Agency Sitemap</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            color: #fff;
            background-color: #000;
            margin: 0;
            padding: 40px;
          }
          a {
            color: #C6A87C;
            text-decoration: none;
            transition: all 0.3s ease;
          }
          a:hover {
            color: #fff;
            text-decoration: underline;
          }
          h1 {
            color: #C6A87C;
            font-size: 32px;
            margin-bottom: 20px;
            letter-spacing: -1px;
          }
          .description {
            color: #888;
            margin-bottom: 40px;
            font-size: 14px;
          }
          table {
            border-collapse: collapse;
            width: 100%;
            max-width: 1200px;
            margin-top: 20px;
            border: 1px solid #333;
          }
          th {
            background-color: #111;
            color: #fff;
            text-align: left;
            padding: 15px;
            border-bottom: 1px solid #333;
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 1px;
          }
          td {
            padding: 12px 15px;
            border-bottom: 1px solid #222;
            font-size: 14px;
            color: #ccc;
          }
          tr:hover td {
            background-color: #111;
          }
          .count {
            display: inline-block;
            background: #C6A87C;
            color: #000;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 12px;
            font-weight: bold;
            margin-left: 10px;
          }
        </style>
      </head>
      <body>
        <h1>ZMK Agency XML Sitemap <span class="count"><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> Pages</span></h1>
        <p class="description">
          Google ve arama motorları için optimize edilmiş, ZMK Agency site haritası. 
          <br/>
          Generated by ZMK Ultra System.
        </p>
        <table>
          <thead>
            <tr>
              <th width="60%">URL</th>
              <th width="15%">Priority</th>
              <th width="15%">Change Freq</th>
              <th width="10%">Last Mod</th>
            </tr>
          </thead>
          <tbody>
            <xsl:for-each select="sitemap:urlset/sitemap:url">
              <tr>
                <td>
                  <xsl:variable name="itemURL">
                    <xsl:value-of select="sitemap:loc"/>
                  </xsl:variable>
                  <a href="{$itemURL}">
                    <xsl:value-of select="sitemap:loc"/>
                  </a>
                </td>
                <td>
                  <xsl:value-of select="concat(sitemap:priority*100,'%')"/>
                </td>
                <td>
                  <xsl:value-of select="sitemap:changefreq"/>
                </td>
                <td>
                  <xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/>
                </td>
              </tr>
            </xsl:for-each>
          </tbody>
        </table>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
